dataset:
  train_frac: 0.8

model:
  type: Proximity300x300
  embedding_size: 128

loss:
  type: OnlineTripletLoss
  margin: 0.2

training:
  seed: 0
  n_epochs: 50
  batch:
    n_classes: 2
    n_samples: 4
  optimizer:
    type: adam
    lr: 1e-5
    weight_decay: 1e-4
  scheduler:
    step_size: 50
    gamma: 0.1
  metrics:
    - name: Loss
    - name: AverageNonzeroTripletsMetric
    - name: TotalNonzeroTripletsMetric
    - name: AllMetrics
      args:
        label_dict: PROXIMITY_VECTOR_LABELS_FOR_TRAINING
        class_names: PROXIMITY_CLASS_NAMES
  train_full_loader_switch: False

paths:
  user_home: /dataChivo/jpmunoz
  base_data: /dataChivo/batch_01/bigdata_02/datareleases
  project_root: /dataChivo/jpmunoz/chest_ct_retrieval

  dr2156:
    datarelease: chest_ct_retrieval/DR2156
    ct: chest_ct_retrieval/DR2156_studies
    labels: chest_ct_retrieval/DR2156_labels/DR2156_labels.csv
    preprocessed_300: chest_ct_retrieval/data/DR2156/DR2156_300_preprocessed
    preprocessed_512: chest_ct_retrieval/data/DR2156/DR2156_512_preprocessed
    embeddings_300: chest_ct_retrieval/data/DR2156/DR2156_300_resnet18_embeddings
    embeddings_512: chest_ct_retrieval/data/DR2156/DR2156_512_resnet18_embeddings
    triplet_runs: chest_ct_retrieval/runs

logging:
  log_interval: 10