dataset:
  train_frac: 0.8

model:
  type: Proximity100x100
  embedding_size: 512

loss:
  type: OnlineTripletLoss
  margin: 0.2

training:
  seed: 0
  n_epochs: 50
  augmentations: True
  batch:
    n_classes: 2
    n_samples: 3
  optimizer:
    type: adam
    lr: 1e-5
    weight_decay: 1e-4
  scheduler:
    step_size: 50
    gamma: 0.1
  metrics:
    loss: True
    average_nonzero_triplets: True
    total_nonzero_triplets: True
    ndcg: False
    recall: False
    all_metrics: True
  train_full_loader_switch: False

paths:
  user_home: E:\\files\Documents\\Proyecto Proximity\\
  base_data: \\dataChivo\\batch_01\\bigdata_02\\datareleases
  project_root: E:\\files\Documents\\Proyecto Proximity\\chest_ct_retrieval

  dr2156:
    datarelease: DR2156
    ct: DR2156_studies
    labels: DR2156_labels\\DR2156_labels.csv
    preprocessed_300: data\\DR2156\\DR2156_300_preprocessed
    preprocessed_300_int8: data\\DR2156\\DR2156_300_preprocessed_int8
    preprocessed_300_zarr: data\\DR2156\\DR2156_300_preprocessed_zarr
    preprocessed_512: data\\DR2156\\DR2156_512_preprocessed
    embeddings_300: data\\DR2156\\DR2156_300_resnet18_embeddings
    embeddings_512: data\\DR2156\\DR2156_512_resnet18_embeddings
    triplet_runs: runs

logging:
  log_interval: 10